version: '3.8'

services:
    nginx:
        image: nginx:stable-alpine
        ports:
            - "8099:80"
        volumes:
            - ./:/app
            - ./docker/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - db

    php:
        build: docker/php
        volumes:
            - ./:/app:cached

    db:
        image: mysql:8.0
        restart: unless-stopped
        ports:
            - "3307:3306"
        volumes:
            - db_data:/var/lib/mysql:cached
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_DATABASE: "${DB_DATABASE}"

volumes:
    db_data:
